### ISSUE TITLE
I have this error when using archinstall

### ISSUE THREAD

**Issue by castillofrancodamian** [archlinux/archinstall#1212]
```
Enabling service fstrim.timer
['/usr/bin/arch-chroot', '/mnt/archinstall', 'mkinitcpio', '-P'] exited with abnormal exit code [32512]: b"chroot: failed to run command 'mkinitcpio': No such file or directory\r\n"
[!] Se ha creado un archivo de registro aquí: /var/log/archinstall/install.log
    Por favor envíe este problema (y archivo) a https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/archinstall/archinstall/__main__.py", line 15, in <module>
    archinstall.run_as_a_module()
  File "/root/archinstall/./archinstall/__init__.py", line 278, in run_as_a_module
    script.execute()
  File "/root/archinstall/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/archinstall/archinstall/examples/guided.py", line 311, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/root/archinstall/archinstall/examples/guided.py", line 138, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/root/archinstall/archinstall/lib/installer.py", line 159, in __exit__
    raise args[1]
  File "/root/archinstall/archinstall/examples/guided.py", line 188, in perform_installation
    if installation.minimal_installation(testing=enable_testing, multilib=enable_multilib):
  File "/root/archinstall/archinstall/lib/installer.py", line 734, in minimal_installation
    self.mkinitcpio('-P')
  File "/root/archinstall/archinstall/lib/installer.py", line 630, in mkinitcpio
    return SysCommand(f'/usr/bin/arch-chroot {self.target} mkinitcpio {" ".join(flags)}').exit_code == 0
  File "/root/archinstall/archinstall/lib/general.py", line 416, in __init__
    self.create_session()
  File "/root/archinstall/archinstall/lib/general.py", line 467, in create_session
    with SysCommandWorker(
  File "/root/archinstall/archinstall/lib/general.py", line 273, in __exit__
    raise SysCallError(f"{self.cmd} exited with abnormal exit code [{self.exit_code}]: {self._trace_log[-500:]}", self.exit_code)
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'mkinitcpio', '-P'] exited with abnormal exit code [32512]: b"chroot: failed to run command 'mkinitcpio': No such file or directory\r\n"
python -m archinstall  29.07s user 31.11s system 13% cpu 7:14.44 total
```

**Comment by Torxed** [comment]
Can you submit the log file https://archinstall.readthedocs.io/help/issues.html#log-files? Or the `/var/log/archinstall/user_configuration.json` *(just make sure they don't contain passwords first)*

**Comment by castillofrancodamian** [comment]
> Can you submit the log file https://archinstall.readthedocs.io/help/issues.html#log-files? Or the `/var/log/archinstall/user_configuration.json` _(just make sure they don't contain passwords first)_

```
root@archiso ~ # cat /var/log/archinstall/user_configuration.json
{
    "__separator__": null,
    "additional-repositories": [
        "multilib",
        "testing"
    ],
    "archinstall-language": "Spanish",
    "audio": null,
    "bootloader": "grub-install",
    "config_version": "2.4.2",
    "debug": false,
    "harddrives": [
        "/dev/sda"
    ],
    "hostname": "netbook",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "es",
    "mirror-region": {
        "Brazil": {
            "http://archlinux.c3sl.ufpr.br/$repo/os/$arch": true,
            "http://archlinux.pop-es.rnp.br/$repo/os/$arch": true,
            "http://br.mirror.archlinux-br.org/$repo/os/$arch": true,
            "http://linorg.usp.br/archlinux/$repo/os/$arch": true,
            "http://mirror.ufscar.br/archlinux/$repo/os/$arch": true
        }
    },
    "mount_point": null,
    "nic": [
        {
            "dhcp": false,
            "dns": [
                "192.168.1.1"
            ],
            "gateway": "192.168.1.1",
            "iface": "enp1s0",
            "ip": "192.168.1.11/24",
            "type": "manual"
        }
    ],
    "ntp": true,
    "packages": [
        "htop",
        "nano",
        "docker",
        "docker-compose",
        "neofetch",
        "screenfetch"
    ],
    "plugin": null,
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/minimal.py"
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": false,
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "America/Argentina/Buenos_Aires",
    "version": "2.4.2"
}#       
```

**Comment by Torxed** [comment]
Turn off the testing repository, it causes an issue that makes installing packages impossible sadly. It will be corrected in the next release.

**Comment by adocampo** [comment]
I'm having the same issue as the OP. I've already disable both testing and multilib repositories, but no luck.
My log and configuration down below.

[user_configuration.json.txt](https://github.com/archlinux/archinstall/files/9508745/user_configuration.json.txt)
[install.log.txt](https://github.com/archlinux/archinstall/files/9508746/install.log.txt)

Just notice I'm installing arch on a kvm VM under proxmox. My disks are Virtio, which are supposed to work better than scsi, anyway I've tried both, but both fails.

**Comment by Torxed** [comment]
@adocampo It looks like you're using a bit of an older configuration, or have you omitted some values by choice?
You're missing `bootloader` and things like `kernels`. I'm actually not entirely sure what `archinstall` will do if none of these exist. I should probably know but I've never ran that scenario so I hope it will default to something.

But that leads me to believe that the config is very old?

Either way, the `testing` issue described here still exists on the officla ISO, it's only fixed in `master` and we're about to release the version that fixes this *(it's been a lot of vacation and other delaying factors)*.

**Comment by adocampo** [comment]
Well, I don't know why is an outdated configuration, I've downloaded the latest ISO and ran archinstall right away, And saved the configuration file through the menu. I'm not avoiding nor kernel nor boot loader, I don't know why isn't shown on the json
![imagen](https://user-images.githubusercontent.com/2266612/188961423-f8c87339-87f0-4423-9ef5-4f44d49e7e96.png)

**Comment by adocampo** [comment]
I think it's a bug on the save function. I've entered the menu and selected the linux kernel and bootloader and saved the configuration file again, now it shows both entries.
[user_configuration.json.txt](https://github.com/archlinux/archinstall/files/9509106/user_configuration.json.txt)

Unfortunately, it still fails just after trying to start `fstrim.timer`.

**Comment by adocampo** [comment]
Oh, just rebooted and repeated the process once again, making sure I've entered all the menu entries _and_ not chosing any extra repo. Now it works.

Thank you!

**Comment by saladuit** [comment]
![20230720_040303.jpg](https://github.com/archlinux/archinstall/assets/43225170/a7467ecf-d15c-427e-9a1d-4e61e6807d9b)

I still get this error. Tried rebooting. Only selecting minimal options, selecting amixture of options. Enabling it from the terminal just works. So not understanding why it doesnt work from the script.

**Comment by adocampo** [comment]
which optiona repositories did you choose? which version of the installer are you running?
