### ISSUE TITLE
[256]: b'mount: /mnt/archinstall/dev: udev already mounted on /mnt/archinstall/dev

### ISSUE THREAD

**Issue by erikdubois** [archlinux/archinstall#1495]
Have a look at this error message.

It may tell you what went wrong and a clue how to improve the code

https://youtu.be/XxIh-B4Ol1g

Second install in same video worked again.

![test](https://user-images.githubusercontent.com/10594806/192700526-9edfdbc5-719a-4fc0-94d1-cbb4c37d5951.png)

**Comment by Torxed** [comment]
Yea this one is a fun one :) It's a stack trace of a forked process.
I've seen it happen a few times, I have a hunch of what's wrong.

I'm assuming since you build the ISO in the video that you used the latest package 2.5.1, and it's not old footage you just uploaded?

**Comment by erikdubois** [comment]
sorry about not mentioning the numbers.

I have build the Arch Linux iso my self - https://youtu.be/XxIh-B4Ol1g

looking at the iso I got archinstall 2.5.1-1

**Comment by Torxed** [comment]
> idea: why no let the script start with the version number so it can be in the video

Thought about it when I was asking hehe.
Normally we ask people to submit the `install.log` where that information exists tho :) But perhaps we can put it in a corner or something.

**Comment by acfuns** [comment]
same error

**Comment by VexfulNiko** [comment]
Same here
Dell Optiplex 3080

**Comment by nonwibb** [comment]
I'm getting the same error. I tried it on two different drives and even reflashed my usb. It's the Oct 1 arch iso release. I used the same settings and hardware with an older iso and it worked.

**Comment by Torxed** [comment]
Can anyone submit your conf and disk layout?

https://archinstall.readthedocs.io/help/issues.html

**Comment by Torxed** [comment]
![screenshot](https://user-images.githubusercontent.com/861439/194324716-21a4a1aa-6cdc-4ed1-a8d6-abe08c593ade.png)

I suspect this change to be a potential candidate for the root cause.
Because we don't update it in real time, but rely on static information:  https://github.com/archlinux/archinstall/blob/977976f88e761ced7d5bc9f39b32e2296ee91806/archinstall/lib/disk/partition.py#L35-L38

**Comment by Torxed** [comment]
Temporary hotfix, in `partition.py` add:
```python
def mount(self, target :str, fs :Optional[str] = None, options :str = '') -> bool:
	SysCommand(f"umount {self._path}")
	if not self._partition_info.get_first_mountpoint():
```
And that should at least unmount the device first.

**Comment by Betablockr** [comment]
Unfortunately (unless I did it wrong this time around) the hotfix isn't 100% perfect. The first 3 runs I did was fine. After deleting the iso by accident, re-downloading and nano thr file I now get the same error despite the fix. I may just be typing it in wrong though. 

Also may not be an archinstall thing but after booking windows it seems to erase thr drive. Not even able to grab the EFI manually in BIOS

**Comment by martabal** [comment]
Same error for me.

**Comment by VexfulNiko** [comment]
I fixed the error for my setup on the optiplex by doing the root account setup first then the drivers then the profile and parallel download along side the time config and then the user account and that worked but doing it from order (drive first then follow the list down) didn't work, very weird.

**Comment by luisnabais** [comment]
I have the same issue, using a 1TB SSD M.2.

Here is My error message:
```
Warning: --debug mode will write certain credentials to /var/log/archinstall/install.log!
Testing connectivity to the Arch Linux mirrors ...
 ! Formatting [BlockDevice(/dev/nvme0n1, size=931.5GB, free_space=1031kB+999GB, bus_type=nvme)] in 5....4....3....2....1....
Creating a new partition label on /dev/nvme0n1
Adding partition to BlockDevice(/dev/nvme0n1, size=931.5GB, free_space=1031kB+999GB, bus_type=nvme), 1MiB->1024MiB
Could not find the new PARTUUID after adding the partition.
Previous partitions: []
New partitions: {None}
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 311, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 315, in <module>
    perform_filesystem_operations()
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 130, in perform_filesystem_operations
    with archinstall.Filesystem(drive, mode) as fs:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 44, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 131, in perform_filesystem_operations
    fs.load_layout(archinstall.arguments['disk_layouts'][drive.path])
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 89, in load_layout
    partition['device_instance'] = self.add_partition(partition.get('type', 'primary'),
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 285, in add_partition
    raise DiskError(f"Could not add partition using: {parted_string}")
archinstall.lib.exceptions.DiskError: Could not add partition using: /dev/nvme0n1 mkpart primary fat32 1MiB 1024MiB
```

My configuration:
``` json
{
    "archinstall-language": "English",
    "audio": "pipewire",
    "bootloader": "grub-install",
    "config_version": "2.5.1",
    "debug": false,
    "desktop-environment": "gnome",
    "gfx_driver": "Intel (open-source)",
    "harddrives": [
        "/dev/nvme0n1"
    ],
    "hostname": "thinkarch",
    "kernels": [
        "linux-lts"
    ],
    "keyboard-layout": "pt-latin1",
    "mirror-region": {
        "Portugal": {
            "http://ftp.rnl.tecnico.ulisboa.pt/pub/archlinux/$repo/os/$arch": true,
            "http://glua.ua.pt/pub/archlinux/$repo/os/$arch": true,
            "http://mirrors.up.pt/pub/archlinux/$repo/os/$arch": true,
            "https://ftp.rnl.tecnico.ulisboa.pt/pub/archlinux/$repo/os/$arch": true,
            "https://glua.ua.pt/pub/archlinux/$repo/os/$arch": true,
            "https://mirrors.up.pt/pub/archlinux/$repo/os/$arch": true
        }
    },
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/desktop.py"
    },
    "script": "guided",
    "silent": false,
    "swap": true,
    "timezone": "Europe/Lisbon",
    "version": "2.5.1"
}
```

and my disk layout:
``` json
{
    "/dev/nvme0n1": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "1024MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "btrfs": {
                    "subvolumes": [
                        {
                            "compress": false,
                            "mountpoint": "/",
                            "name": "@",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/home",
                            "name": "@home",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/var/log",
                            "name": "@log",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/var/cache/pacman/pkg",
                            "name": "@pkg",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/.snapshots",
                            "name": "@.snapshots",
                            "nodatacow": false
                        }
                    ]
                },
                "encrypted": true,
                "filesystem": {
                    "format": "btrfs",
                    "mount_options": [
                        "compress=zstd"
                    ]
                },
                "mountpoint": null,
                "size": "100%",
                "start": "1025MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
```

**Comment by Betablockr** [comment]
> I fixed the error for my setup on the optiplex by doing the root account setup first then the drivers then the profile and parallel download along side the time config and then the user account and that worked but doing it from order (drive first then follow the list down) didn't work, very weird.

Wait so giving root access first, by making the root account in the list first is what fixed it for you? Are you able to recreate these steps and does this method work every time? If so then maybe the issue is a security one?? I may be totally incorrect.

**Comment by goebeler** [comment]
> Temporary hotfix, in `/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py` add:
> 
> warning _Note that if you use subvolumes, this hotfix will not work because a partition is expected to be remounted a couple of times but with different `subvol=<id>`_!
> 
> ```python
> def mount(self, target :str, fs :Optional[str] = None, options :str = '') -> bool:
> -->	try:
> -->		SysCommand(f"umount {self._path}")
> -->	except:
> -->		pass
> 	if not self._partition_info.get_first_mountpoint():
> ```
> 
> And that should at least unmount the device first.

Same propblem here, regardless of the actual partition layout, and unfortunately the hotfix did not solve it.

**Comment by Torxed** [comment]
Another more annoying workaround is to manually partition the drive and mount the volumes at `/mnt/archinstall` and `/mnt/archinstall/boot`.

And in `archinstall`, enter the disk selection step and press ` trl+C` to skip it :)

**Comment by Torxed** [comment]
So I've looked over some of the `install.log` and mainly `cmd_history.txt` some more.
And it turns out:
```
Formatting /dev/nvme0n1p1 -> vfat
...
Formatting /dev/nvme0n1p1 -> ext4
```
And a weird artifact of that is:
```
Mounting Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=f451088e-c21d-4067-94dc-1a898a697062, fs=ext4) to /mnt/archinstall/
Mounting Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=f451088e-c21d-4067-94dc-1a898a697062, fs=vfat) to /mnt/archinstall/boot
```

`archinstall` things the `Partition()` instance are unique, and thus differently formatted with different filesystems.
But the `PARTUUID` the instance belongs to are the same. And the `._path` is the same.

As of now I have no clue why that happens.
And why it's unique to NVMe drives *(and not even all of them, I've tried separate machines with NVMe and can't reproduce it. But a kind soul on discord has lent me two days of his time who can reproduce it reliably)*.

I suspect it's this change at the moment:
![screenshot](https://user-images.githubusercontent.com/861439/194769354-c8813581-fa04-423a-90ca-293bb13ac2ab.png)

**Comment by Torxed** [comment]
A workaround that definitely works but is a bit more technical:

1) Manually partition the disk with any other tool (like `parted`)
2) Mount a root partition to `/mnt/archinstall` and a boot partition to `/mnt/archinstall/boot` *(don't forget to create the boot folder)*
3) Run `archinstall` and navigate to the disk selection step
4) Press `Ctrl` + `C` to abort the disk selection and it will ask if you want to skip this step, press `yes`
5) Continue with the installation as per normal

`archinstall` will in this case not perform any disk operations and use whatever partitions you mounted.

**Comment by guihkx** [comment]
> And why it's unique to NVMe drives _(and not even all of them, I've tried separate machines with NVMe and can't reproduce it. But a kind soul on discord has lent me two days of his time who can reproduce it reliably)_.

I don't have a NVMe drive and I'm experiencing this right now. I'm just trying to create an Arch Linux VM using GNOME Boxes. It's failed twice with the exact same error.

- Arch ISO: `archlinux-2022.10.01-x86_64.iso`
- archinstall: `v2.5.1`
- archinstall logs/configs: [archinstall.zip](https://github.com/archlinux/archinstall/files/9754443/archinstall.zip)
- `dmesg` output: [dmesg.txt](https://github.com/archlinux/archinstall/files/9754467/dmesg.txt)

**Comment by guihkx** [comment]
> And why it's unique to NVMe drives _(and not even all of them, I've tried separate machines with NVMe and can't reproduce it. But a kind soul on discord has lent me two days of his time who can reproduce it reliably)_.

I don't have a NVMe drive and I'm experiencing this right now. I'm just trying to create an Arch Linux VM using GNOME Boxes. It's failed twice with the exact same error.

- Arch ISO: `archlinux-2022.10.01-x86_64.iso`
- archinstall: `v2.5.1`
- archinstall logs/configs: [archinstall.zip](https://github.com/archlinux/archinstall/files/9754527/archinstall.zip)
- `dmesg` output: [dmesg.txt](https://github.com/archlinux/archinstall/files/9754467/dmesg.txt)

**Comment by guihkx** [comment]
>May I ask, are you using an SSD or HDD?

The QEMU disk image is stored on my external hard drive of 7200 RPM. It uses NTFS as the filesystem and just to make things \~really~ fast, it's mounted using the `ntfs-3g` userspace driver instead of the `ntfs3` kernel driver... 😅

**Comment by Betablockr** [comment]
> > May I ask, are you using an SSD or HDD?
> 
> The QEMU disk image is stored on my external hard drive of 7200 RPM. It uses NTFS as the filesystem, and just to make things ~extra~ fast, it's mounted using the `ntfs-3g` FUSE driver instead of the `ntfs3` kernel driver... 😅

Don't know if I'm follwing right but are you using the external drive to run the ISO? Is the drive you installing too a HDD or SATA SSD?

**Comment by Torxed** [comment]
![screenshot](https://user-images.githubusercontent.com/861439/195124179-dfab66c4-5ad1-4bfc-b71f-ce1c7175cd5c.png)

reintroducing the following code appears to help (but slows down `archinstall`).

**Comment by cristianelias** [comment]
> A workaround that definitely works but is a bit more technical:
> 
> 1. Manually partition the disk with any other tool (like `parted`)
> 2. Mount a root partition to `/mnt/archinstall` and a boot partition to `/mnt/archinstall/boot` _(don't forget to create the boot folder)_
> 3. Run `archinstall` and navigate to the disk selection step
> 4. Press `Ctrl` + `C` to abort the disk selection and it will ask if you want to skip this step, press `yes`
> 5. Continue with the installation as per normal
> 
> `archinstall` will in this case not perform any disk operations and use whatever partitions you mounted.

Thank you very much for your efforts and clear explanation 🙌🏻 👑

**Comment by Torxed** [comment]
Merged into `master` and I'm pushing a new release now, which should fix this.

**Comment by guihkx** [comment]
Just confirming that with [this ISO](https://github.com/archlinux/archinstall/actions/runs/3234933961), installing Arch on GNOME Boxes now goes very smoothly with no errors! Previously, I would consistently hit this error, but on the two different virtual machines I've created so far, the error didn't pop up. Log/config files, just in case:

- [archinstall.tar.gz](https://github.com/archlinux/archinstall/files/9765715/archinstall.tar.gz)

**Comment by SailReal** [comment]
v2.5.2 fixed it for me too. Thank you very much!

**Comment by Torxed** [comment]
I'm glad to hear and thank you for testing :D 
Better part of two weeks have been dedicated to this >_O
