### ISSUE TITLE
Failed to read disk "/dev/sdaX" with lsblk

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1557]
Unsure of how or why, but a user reports issues with `/dev/sda1` being called onto when it doesn't appear to exist.

Stack trace:
```
Exit code for blkid -p -o export was: 512
Not a loop device, trying uevent rules.
Could not decode JSON: lsblk: /dev/sda1: not a block device
{
   "blockdevices": [

   ]
}

Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 311, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 301, in <module>
    ask_user_questions()
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 107, in ask_user_questions
    global_menu.run()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 336, in run
    if not self._process_selection(value):
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 353, in _process_selection
    return self.exec_option(config_name, selector)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/selection_menu.py", line 373, in exec_option
    result = selector.func(presel_val)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/global_menu.py", line 79, in <lambda>
    lambda preset: self._select_harddrives(preset),
  File "/usr/lib/python3.10/site-packages/archinstall/lib/menu/global_menu.py", line 345, in _select_harddrives
    harddrives = select_harddrives(old_harddrives)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/user_interaction/system_conf.py", line 52, in select_harddrives
    hard_drives = all_blockdevices(partitions=False).values()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/helpers.py", line 275, in all_blockdevices
    instances[path] = BlockDevice(path, path_info)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py", line 53, in __init__
    self._load_partitions()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py", line 131, in _load_partitions
    self._partitions[part_id] = Partition(root + part_id, block_device=self, part_id=part_id)
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 102, in __init__
    self._partition_info = self._fetch_information()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 213, in _fetch_information
    lsblk_info = self._call_lsblk()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py", line 195, in _call_lsblk
    raise DiskError(f'Failed to read disk "{self.device_path}" with lsblk')
archinstall.lib.exceptions.DiskError: Failed to read disk "/dev/sda1" with lsblk
```

`/dev/` says:
```
brw-rw----  1 root disk      8,   0 Nov  6 09:24 sda
brw-rw----  1 root disk      8,   2 Nov  6 09:24 sda2
```

`/sys/class/blockdev/` says:
```
lrwxrwxrwx 1 root root 0 Nov  6 09:21 loop0 -> ../../devices/virtual/block/loop0
lrwxrwxrwx 1 root root 0 Nov  6 09:21 nvme0n1 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1
lrwxrwxrwx 1 root root 0 Nov  6 09:24 nvme0n1p1 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p1
lrwxrwxrwx 1 root root 0 Nov  6 09:24 nvme0n1p2 -> ../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/nvme/nvme0/nvme0n1/nvme0n1p2
lrwxrwxrwx 1 root root 0 Nov  6 09:21 sda -> ../../devices/pci0000:00/0000:00:07.1/0000:1d:00.3/usb4/4-4/4-4:1.0/host10/target10:0:0/10:0:0:0/block/sda
lrwxrwxrwx 1 root root 0 Nov  6 09:21 sda2 -> ../../devices/pci0000:00/0000:00:07.1/0000:1d:00.3/usb4/4-4/4-4:1.0/host10/target10:0:0/10:0:0:0/block/sda/sda2
lrwxrwxrwx 1 root root 0 Nov  6 09:21 sr0 -> ../../devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-8/1-8:1.2/host9/target9:0:0/9:0:0:0/block/sr0
```

Here are the error logs reported:
* http://ix.io/4f5L
* http://ix.io/4f5S
* http://ix.io/4f5U

**Comment by svartkanin** [comment]
I've seen this one before as well, I managed to solve it with retries actually

**Comment by Torxed** [comment]
Yea that appears to be the general fix. But I'm wondering if it's a corrupt `--conf` or something? Hardcoded entries from the past?

**Comment by mj-linux** [comment]
Me too having same issue, was able to install after few re tries.

**Comment by lucazade** [comment]
same here, tried again a couple of times but no luck :/

**Comment by Torxed** [comment]
@mj-linux & @lucazade did you both navigate through the menu system or use a `--conf` approach with an old disk layout/conf? :)

**Comment by lucazade** [comment]
@Torxed I used the menu to configure disk and partition

**Comment by mj-linux** [comment]
@Torxed i used menu to configure, wipe all selected drives and use best-effort......

**Comment by mj-linux** [comment]
tried to install in VM, now archinstall is completely broken.
re tries also not working.
![image](https://user-images.githubusercontent.com/97375125/201991083-7254d19f-ec36-4a16-a814-44895dd9fa3e.png)

**Comment by Torxed** [comment]
> tried to install in VM, now archinstall is completely broken. re tries also not working. ![image](https://user-images.githubusercontent.com/97375125/201991083-7254d19f-ec36-4a16-a814-44895dd9fa3e.png)

That issue is related to: https://github.com/archlinux/archinstall/issues/1389

**Comment by Torxed** [comment]
> @Torxed i used menu to configure, wipe all selected drives and use best-effort......

Thank you, this will make testing easy! :D

**Comment by phromaj** [comment]
Hi, I’m having exactly the same error. Did not work after many tries. 
It tries to decode /dev/sda1 with lsblk but I don’t have any partition mounted on it. I think that is the problem.

**Comment by maximebories** [comment]
Same here on bare-metal, tried enought times to be sure it doesn't work at all.  Tried resetting the keyring as mentioned in https://github.com/archlinux/archinstall/issues/1389:

```
killall gpg-agent
pacman-key --init
pacman-key --populate archlinux
pacman -Syy
```

And... no difference. I hadn't gone thought the manual install for a long time !

**Comment by svartkanin** [comment]
@colossalchicken #1434 has nothing to do with it as it's an open PR that hasn't even been merged into master

**Comment by schumischumi** [comment]
same problem, but it still works fine with the old image archlinux-2022.11.01-x86_64.iso after updating the keyring

**Comment by phromaj** [comment]
> same problem, but it still works fine with the old image archlinux-2022.10.01-x86_64.iso after updating the keyring

Yes I tried this morning with archlinux september image and it worked flawlessly.

**Comment by Alf0nso** [comment]
hey hey, I had the same issue. Every time I try to access the "Drive(s)" option, it breaks and shows the same error.
The machine where I am installing arch has "nvme0n1" as a name. Does the "archinstall" script only looks for sdX?

**Comment by featherfurl** [comment]
I have the same issue also. It seems to work after retrying on my main PC, but when installing on my older systems it always fails halfway through the install process with the same lsblk error.

**Comment by jamiesteven** [comment]
I was able to "workaround" using the latest archiso by patching archinstall's use of the lsblk command to exclude the offending device using the -e option.

- determine the disk device that's throwing the error using lsblk during archinstall, and get MAJ value from running lsblk. For me, it was my /dev/sda USB flash drive, MAJ=8.
- edit ``/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py``, replace:
```output = SysCommand(f'lsblk --json -b -o+SIZE,PTTYPE,ROTA,TRAN,PTUUID {self._path}').decode('UTF-8')```
with
```output = SysCommand(f'lsblk -a -e 8 --json -b -o+SIZE,PTTYPE,ROTA,TRAN,PTUUID {self._path}').decode('UTF-8')```
- The -"e 8" removes MAJ device 8, and should fix this error from occurring later during install. Obviously, replace the 8 with the device you'd like to exclude from crashing archinstall.
- edit ``/usr/lib/python3.10/site-packages/archinstall/lib/disk/partition.py``, replace:
```lsblk_info = SysCommand(f"lsblk --json -b -o+LOG-SEC,SIZE,PTTYPE,PARTUUID,UUID,FSTYPE {self.device_path}").decode('UTF-8')```
with
```lsblk_info = SysCommand(f"lsblk -a -e 8 --json -b -o+LOG-SEC,SIZE,PTTYPE,PARTUUID,UUID,FSTYPE {self.device_path}").decode('UTF-8')```
Same as before.
- run ``archinstall`` with config file specifically for the drive you'd like to use, i.e. specify the harddrives field. You can then avoid having to use the Drive selector, and crashing archinstall. ``archinstall --config config.json``:
```
config.json
{
  "harddrives": [
        "/dev/targetdrivename"
    ]
}
```

Perhaps these modifications will work for others. You can find other innovations of ``lsblk`` (to patch) using search: https://github.com/archlinux/archinstall/search?q=lsblk

**Comment by Torxed** [comment]
A good workaround. I'll still need to figure out where our logical issue is as to why `archinstall` even thinks `/dev/sda1` exists when it doesn't (as an example).

I believe it's back to the old issues of a cache being present somewhere, and `archinstall` is acting on incorrect information.

**Comment by jmayday** [comment]
Same here :( I tried retrying, but it still fails when I start installation (or even at earlier stage when I set-up disk in archinstall).

**Comment by jmayday** [comment]
> I've seen this one before as well, I managed to solve it with retries actually

In my case it was failing on disk/partition layout setup. It didn't fail after retrying that's right, but it failed anyway at later stage (after triggering proper installation). I guess I will just wait for fix.

**Comment by jamiesteven** [comment]
Here are improved instructions to patch this issue until it's fixed:
1. Boot archiso.
2. Run ``lsblk``:
```
root@archiso ~ # lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0         7:0    0 705.6M  1 loop /run/archiso/airootfs
sda           8:0    1  29.9G  0 disk
└─sda2        8:2    1    15M  0 part
nvme0n1     259:0    0 476.9G  0 disk
├─nvme0n1p1 259:1    0   100M  0 part
├─nvme0n1p2 259:2    0   128M  0 part
├─nvme0n1p3 259:3    0   475G  0 part
└─nvme0n1p4 259:4    0   1.7G  0 part
```
3. Observe the MAJ number of the device that causes archinstall to fail. For me, it was the /dev/sda flash drive which archiso booted off of. I note that /sda has a MAJ value of 8.
4. Run this patch command, editing the ``-e 8`` portion to match the MAJ of the device that's erroring for you.
Note: this command recursively edits every instance of lsblk run by archinstall to exclude the specific device.
```find /usr/lib/python3.10/site-packages/archinstall/ -type f -exec sed -i "s/lsblk --json/lsblk -a -e 8 --json/g" {} \;```
5. Run ``archinstall`` and install on the desired drive.

**Comment by stepan-zubkov** [comment]
@jamiesteven 
I have same error with /dev/sdb (My flash drive with arch iso).

In lsblk, /dev/sda and /dev/sdb have same major version. Will your solution help me?

**Comment by saghul** [comment]
I had the same issue recently @stepan-zubkov .

What worked for me was to use the September or October ISO. Worked on the second try.

**Comment by lucazade** [comment]
> A good workaround. I'll still need to figure out where our logical issue is as to why `archinstall` even thinks `/dev/sda1` exists when it doesn't (as an example).
> 
> I believe it's back to the old issues of a cache being present somewhere, and `archinstall` is acting on incorrect information.

From what I've seen this issue is not only related to sda1 but also to other devices like sdb1, it seems a bit randomic in different trials I made..
It is really a showstopper preventing me to install via archinstall :|

@Torxed do you need any other info or logs to debug it? Or how can we help?

**Comment by Torxed** [comment]
I think I have everything I need, I just need to find some free time to debug and develop stuff. I'll try my best to spend some time this weekend! But I can't promise a solution by then.

**Comment by KenVanHoeylandt** [comment]
I found an even easier fix for my scenario:

The `sda` device for me is the USB key used for booting the ISO. I booted the ISO from USB, then unplugged the USB as it's loaded in memory already. Now `/dev/sda1` is not on my system anymore and the setup doesn't trip over it.

I did run the above scripts just in case, but it might not be needed. I did simplify it further by uploading it to pastebin and curl-ing it in (it's easier than typing all of that):
```
curl https://pastebin.com/raw/1wym5XYx > fix.sh
chmod +x fix.sh
```
Note: Run `cat fix.sh` to verify what's in it, before you run it.

**Comment by frederikhs** [comment]
My install was also fixed by removing the installation medium (USB) after boot. Also check that before moving it is available in `lsblk` and after it is gone.

**Comment by frederikhs** [comment]
I resolved the issue by removing all drives including the installation medium (USB in my case after boot). This resulted in only 1 drive being listed by `lsblk` and the installation finished without any errors.

**Comment by Jamesits** [comment]
It's still happening on archlinux-2022.12.01-x86_64.iso. Removing the USB drive after booting into the live CD solves the issue for me.

**Comment by svartkanin** [comment]
Yes there hasn't been a new release since October. 
There's currently work being done to rewrite large portions of the device handling to utilize the library `pyparted`. This will most definitely solve this issue and many others. Hopefully it will get done within the next week or so and can then be tested

**Comment by heliophane** [comment]
> It's still happening on archlinux-2022.12.01-x86_64.iso. Removing the USB drive after booting into the live CD solves the issue for me.



> I resolved the issue by removing all drives including the installation medium (USB in my case after boot). This resulted in only 1 drive being listed by `lsblk` and the installation finished without any errors.

Could this possibly be resolved by having the script unmount the USB stick? Does the arch installation ISO copy to ram on boot?

**Comment by arcolinuxz** [comment]
A few weeks back Arch Linux changed the way it boots up its iso. That is correct.

https://github.com/archlinux/archiso/commit/2f9cfdf42fce7144f2a83dff08df5af899aceaba

That means Arch Linux now boots from RAM.

The iso of 2022.12.01 loads everything to ram and then archinstall give us the images you see in the post. 
Python crashes.
Adding copytoram=n is our solution to still make ArcoLinux isos with the Calamares installer.

So I thought lets try this

linux /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% copytoram=n

Added the copytoram=n on the fly in grub/uefi of Arch because of the comment of @heliophane  ... but ended up in a python error anyway.
Probably because the sdb usb was still plugged in.

Next attempt was not change anything in the grub lines and booted up - so copytoram is active.
Launched archinstall and unplugged the usb (/dev/sdb).
and installation went well

iso from 22.12.01 - archinstall 2.5.2-1

**Comment by oldwiskas** [comment]
I tried this code many months ago and it worked without issue. Flawless. Now it's not well at all. Sorry if this post seems grumpy, but I was expecting a great experience as I had many months ago, but instead have second-guessed myself and the USBs and the USB ports and the nvme port and the nvme card and _and_ *and* the machine (which runs both Arco [-thanks Erik] and EOS [-thanks guys] just fine).

I think much of the errors seem to stem from when and how it parses for block devices and associated information - and how it references this list elsewhere in the code.

On my laptop (with mixed SATA, NVME and USB "disks"):
If I flash the USB, then boot the ISO from USB, connect WiFi and execute archinstall, it dies because /dev/sdd1 doesn't exist. This is an irrelevant error because we're not installing to that device or that partition (it's the Arch ISO USB)... sooo

If I create /dev/sdd1 and mkfs.ext4, it continues but then doesn't see half the information in the partition list of the selected device (nvme0n1p(x) - that's either a pointer corruption or a parse error.
E.G. ALL of the partitions listed (for the chosen disk) have NO filesystem. (Should be VFAT/FAT32 for boot and ext4 for the rest).

Looking through the code, I can see where it asks "lsblk" to provide this info, so the parsing here has issues. FYI I have run lsblk with the code's specified "qualifiers" or "switches" and... it... never.. fails... ever... on any of the nvme partitions.

Specifying the filesystem format does not necessarily beat this issue. It is seen in a loop that is confused and insistent that seems to be trying to find disks that are irrelevant. 
E.G. Why die looking for /dev/sd<anything> when the device selected is /dev/nvme0n1 ?

It also has another parsing error where it can't match UUIDs and that happens at the beginning of the install process... sometimes?? It shows what's in the list and the UUID is there, so that's got to be some sort of pointer corruption. It's consistently inconsistent.

If it survives that loop (5 times) then it might actually do something. It never finishes. How it dies can change from boot to boot. The latest was a death due to /dev/sdb2 not being a block device (which it is, but both are irrelevant in this case).

In the 10+ times I have tried this process in the last 20 hours, none have worked and all seem to be consistently inconsistent. Not being a python programmer, I have no idea how to track this stuff and am sure that debugging on a "Live" instance of Arch is not my forte anyway.

Logs attached.
[install.log](https://github.com/archlinux/archinstall/files/10174231/install.log)
[cmd_output.txt](https://github.com/archlinux/archinstall/files/10174232/cmd_output.txt)
[cmd_history.txt](https://github.com/archlinux/archinstall/files/10174234/cmd_history.txt)
Configs attached.
[user_disk_layout.json.txt](https://github.com/archlinux/archinstall/files/10174292/user_disk_layout.json.txt)
[user_credentials.json.txt](https://github.com/archlinux/archinstall/files/10174293/user_credentials.json.txt)
[user_configuration.json.txt](https://github.com/archlinux/archinstall/files/10174294/user_configuration.json.txt)

Hopefully this gives some insight. sigh

**Comment by XyroPhyte** [comment]
A workaround I've found is to unplug all drives other than the one Arch will be installed onto after booting into the live environment. It worked for me. As far as I know, this only works for the newer Arch ISOs since older ISOs ran the live environment from the USB instead of RAM

**Comment by viniciuspereiras** [comment]
unplug all drivers works fine for me too :)

**Comment by Zeioth** [comment]
> A workaround I've found is to unplug all drives other than the one Arch will be installed onto after booting into the live environment. It worked for me. As far as I know, this only works for the newer Arch ISOs since older ISOs ran the live environment from the USB instead of RAM

That's great except I'm on a laptot w/ 2 hd. 
No way to use archinstall then?

**Comment by Torxed** [comment]
> > A workaround I've found is to unplug all drives other than the one Arch will be installed onto after booting into the live environment. It worked for me. As far as I know, this only works for the newer Arch ISOs since older ISOs ran the live environment from the USB instead of RAM
> 
> That's great except I'm on a laptot w/ 2 hd. No way to use archinstall then?

I've partially solved this in a branch, but in the meantime you could hide one of the drives in the BIOS. Apologies for the delay in fixing this, but it's on it's way as a separate patch that should make it to the next ISO.

**Comment by xzntrc** [comment]
> unplugging the drives woked for me too.

For some reason it's giving me this error with /dev/sda which is the USB itself. Any fix without having to unplug anything??

**Comment by Jamesits** [comment]
> For some reason it's giving me this error with /dev/sda which is the USB itself. Any fix without having to unplug anything??

You can safely unplug the USB drive too if the installer thinks your computer have enough memory to copy itself into...

**Comment by xzntrc** [comment]
> > For some reason it's giving me this error with /dev/sda which is the USB itself. Any fix without having to unplug anything??
> 
> You can safely unplug the USB drive too if the installer thinks your computer have enough memory to copy itself into...

This isn't only within the archinstall menu, once it's actually installing I get the error too. I can't unplug it in time, in fact the OS crashes when I unplug; I can unplug during menu but not in install.

**Comment by XyroPhyte** [comment]
> I can't unplug it in time, in fact the OS crashes when I unplug; I can unplug during menu but not in install.

If it successfully copied onto RAM it shouldn't crash, I don't know how much RAM your system has so it might also be completely possible that the installer doesn't copy to your RAM and run off the USB drive because you don't have sufficient RAM. The installer is designed to **only** copy to RAM if the installer thinks enough is available. 

If you think you have enough RAM (8GB or more would be) **Try installing with the latest Arch ISO. The older ISOs run from the USB drive instead of RAM.**

**Comment by ShaunTheSalvo** [comment]
Guys - if it's of any help to anyone - I just tried the August 2022 ISO, and it worked perfectly.

All you have to do is run `pacman-key --init`, `pacman-key --populate archlinux`, and then `archinstall`. I've completed two separate installs using this method today, with no trouble whatsoever. Booting from the ISO directly, or through Ventoy, and even installing to an external USB hard drive - works perfectly. I use the "Wipe all drives" option, take your pick which desktop etc you want - no problem at all.

The newer ISO's will work _occasionally_, but I find them very hit and miss. Whatever they did on the August 2022 ISO, they did it right.

I hope this might be helpful. Happy to try more testing etc. if that would help.

**Comment by NIYAZ04** [comment]
Can you tell me at which screen exactly I should remove the bootable pen driver

**Comment by NIYAZ04** [comment]
> Guys - if it's of any help to anyone - I just tried the August 2022 ISO, and it worked perfectly.
> 
> 
> 
> All you have to do is run `pacman-key --init`, `pacman-key --populate archlinux`, and then `archinstall`. I've completed two separate installs using this method today, with no trouble whatsoever. Booting from the ISO directly, or through Ventoy, and even installing to an external USB hard drive - works perfectly. I use the "Wipe all drives" option, take your pick which desktop etc you want - no problem at all.
> 
> 
> 
> The newer ISO's will work _occasionally_, but I find them very hit and miss. Whatever they did on the August 2022 ISO, they did it right.
> 
> 
> 
> I hope this might be helpful. Happy to try more testing etc. if that would help.

**Comment by NIYAZ04** [comment]
> Guys - if it's of any help to anyone - I just tried the August 2022 ISO, and it worked perfectly.
> 
> 
> 
> All you have to do is run `pacman-key --init`, `pacman-key --populate archlinux`, and then `archinstall`. I've completed two separate installs using this method today, with no trouble whatsoever. Booting from the ISO directly, or through Ventoy, and even installing to an external USB hard drive - works perfectly. I use the "Wipe all drives" option, take your pick which desktop etc you want - no problem at all.
> 
> 
> 
> The newer ISO's will work _occasionally_, but I find them very hit and miss. Whatever they did on the August 2022 ISO, they did it right.
> 
> 
> 
> I hope this might be helpful. Happy to try more testing etc. if that would help.





This works for me Thanks a lot man ..
I have been trying to install it from 3 hours man now finally i did it,Once again thank you

**Comment by ShaunTheSalvo** [comment]
> This works for me Thanks a lot man .. I have been trying to install it from 3 hours man now finally i did it,Once again thank you

You're welcome! And good to hear confirmation this is working for others as well.

One thing I noticed, is the options screen layout in the August ISO's archinstall is different to the later ones. Lists of options utilise the entire available screen, not just 4-5 lines at the top like the newer ones do.

Just a suggestion - maybe just rolling back to the archinstall (and whatever else) that was used on the older ISOs for releases of the newer monthly ISOs - might be helpful.

BTW - Happy New Year to all

**Comment by B-Teague** [comment]
Updating archlinux-keyring worked for me
pacman -S archlinux-keyring

**Comment by mltiago** [comment]
Seems that this bug persist in the today 2023.1.1 iso realese.

**Comment by mltiago** [comment]
I keep getting partuuid error.

**Comment by AldairbotHerotaku** [comment]
I just loaded arch in RAM and diconnected th USB and it worked

**Comment by Chais** [comment]
To add to the weirdness: not only does `archinstall` not find partitions that definitely exist, it _actively_ makes them disappear.

![IMG_20230104_192024_HDR.png](https://user-images.githubusercontent.com/1783098/210674876-d729f1fa-8232-40a0-afd2-27d43fb7402f.png)

But yes, just pulling the stick after everything was copied to memory send like the obvious workaround in hindsight.

**Comment by lavafroth** [comment]
Hello. It seems that calling the `partprobe` command is causing the kernel to remove blockdevice entries.

> To add to the weirdness: not only does `archinstall` not find partitions that definitely exist, it _actively_ makes them disappear.

You can use something like `partx` instead, which I included in my pull request. If rereading partitions is desired, consider using `blockdev` with the `rereadpt` flag like `blockdev --rereadpt /dev/sdX`

**Comment by BBQGiraffe** [comment]
tried the USB-pullout solution, can confirm it works

**Comment by MattyPeek** [comment]
Yes USB-pullout works on 2023-01-01 installer for me as well.

**Comment by DrakeAFK** [comment]
As others have mentioned, removing USB drive before running archinstall worked for 2023-01-01 version.

**Comment by Mewsen** [comment]
removing the USB Drive worked.

**Comment by RustyRaptor** [comment]
> But yes, just pulling the stick after everything was copied to memory seems like the obvious workaround in hindsight.

Modern problems require modern solutions.

**Comment by dayatnhbtc** [comment]
> Guys - if it's of any help to anyone - I just tried the August 2022 ISO, and it worked perfectly.
> 
> All you have to do is run `pacman-key --init`, `pacman-key --populate archlinux`, and then `archinstall`. I've completed two separate installs using this method today, with no trouble whatsoever. Booting from the ISO directly, or through Ventoy, and even installing to an external USB hard drive - works perfectly. I use the "Wipe all drives" option, take your pick which desktop etc you want - no problem at all.
> 
> The newer ISO's will work _occasionally_, but I find them very hit and miss. Whatever they did on the August 2022 ISO, they did it right.
> 
> I hope this might be helpful. Happy to try more testing etc. if that would help.

I'm using the latest ISO version, with 3 drives on laptops it works smoothly without having to remove any drives

**Comment by loulou64490** [comment]
Same problem, lot of try...
Please patch 🥺
Thanks 👋

**Comment by malventano** [comment]
> I'm using the latest ISO version, with 3 drives on laptops it works smoothly without having to remove any drives

It will still work for some specific configurations, but the newest ISO still has the issue here.

**Comment by thonkinator** [comment]
i managed to get this to work by removing all erroring drive entries from /dev/. it’ll spit out some warnings about ignoring drives, but it’ll install just fine. this is assuming the erroring drives aren’t the ones you want to install to, of course.

**Comment by ShaunTheSalvo** [comment]
Can confirm this seems to work. Using latest Feb 2023 Arch ISO. Lots of
errors printed in orange during drive formatting about being unable to
locate the /dev entries I remove, but the install runs perfectly otherwise.
Can install to external drive as well if you need.

Start by ensuring you only have drives connected that you need during the
installation, then boot up the Arch ISO. Physically disconnect any unneeded
drives if you can (eg USB external drives or thumb drives).

Steps I followed after booting the Arch ISO from Ventoy USB:

- lsblk to determine which drives are needed for install

- For all other drives:  rm /dev/sdX*

-  Now run archinstall, and set options for installation as you like.

During start-up of archinstall, and at the start of the actual installation
process itself, you may see errors printed in orange about the devices you
removed in the previous step. You can ignore these; the installation should
compete otherwise. Once pacman starts installing packages, you should be
good to go.

God luck!

**Comment by anup-das** [comment]
I have been facing this issue for a long time now ; The old ISO (september 2022 release) works perfectly.  The removal of installation media alone works sometimes with retries.  Additionally all the attached drives ( SATA and external drives if any) also needs to be removed to guarantee success.

I thought that by this time the issue must have been resolved at least partially. Unforunately using this month's release I was unable to install by removing the installation media after boot.  Temporary removal of my other attached internal drives is no longer an option for me (as i do installations quite frequently). I will just go back to september 2022 iso or another distribution :-(

![20230203_145156](https://user-images.githubusercontent.com/63170829/216566431-0f07eddc-279f-4281-8924-4841635d8d88.jpg)

**Comment by dualfade** [comment]
^^ confirmed works --

**Comment by Torxed** [comment]
With the help from another developer, I've now successfully confirmed and can reproduce the issue 100% of the time.
And the root cause is block devices that work as block devices, but are treated as empty types. One such is ISO files converted to a device, they will be a block device but `Type` in `fdisk -l` will be `Empty`, and they will show up in places such as `/sys/class/block/*` but will not be processed by `lsblk` and never show up there.

Here's a snippet from a log:
```
root@archiso ~/archinstall # fdisk -l | grep dev
Disk /dev/sda: 3.92 GiB, 4213178368 bytes, 8228864 sectors
/dev/sda1  *         64 1656831 1656768  809M  0 Empty
/dev/sda2       1656832 1687551   30720   15M ef EFI (FAT-12/16/32)
Disk /dev/loop0: 710.14 MiB, 744632320 bytes, 1454360 sectors
```

```
root@archiso ~/archinstall # lsblk -a
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0         7:0    0 710.1M  1 loop /run/archiso/airootfs
sda           8:0    1   3.9G  0 disk
└─sda2        8:2    1    15M  0 part
```

And in this case `/dev/sda1` would be where the Arch ISO is booted from.
I'll work on the PR #1557 as quickly as I can, and in the future the `pyparted` will work around this issue as well.

Apologies for the major delay, but today was a good day to connect the dots of what the actual cause was. And this confirms why the workaround of removing the USB with Arch Linux on works.

**Comment by inglor** [comment]
Happy to help @Torxed - looking forward on the next release :)

**Comment by Torxed** [comment]
![screenshot](https://user-images.githubusercontent.com/861439/220878278-5c7b4a19-cea6-41bf-a188-5e8eb2d58619.png)

I now ask anyone willing to participate in testing this, to test the ISO containing all the fixes:
* https://github.com/archlinux/archinstall/actions/runs/4251464561

@inglor great work!
And a huge thank you to everyone who submitted logs, was willing to test back and fourth to find the root cause of the issue. Been way to long but the fix is here!

If we can get this verified I can push a release this weekend and it will make it to the 2023-03-01 ISO :)

**Comment by teoteo** [comment]
> Happy to help @Torxed - looking forward on the next release :)

It worked for me too with installer ISO placed on [64GB USB flash drive](https://www.kingston.com/it/support/technical/products/hxs3).
The destination drive where a microSDXC card connected with a [USB card reader](https://www.samsung.com/us/computing/memory-storage/memory-cards/pro-plus---reader-microsdxc-256gb-mb-md256kb-am/). The computer a Beelink U59 N5105 with Windows on internal nVME

**Comment by Torxed** [comment]
> > Happy to help @Torxed - looking forward on the next release :)
> 
> It worked for me too with installer ISO placed on [64GB USB flash drive](https://www.kingston.com/it/support/technical/products/hxs3). The destination drive where a microSDXC card connected with a [USB card reader](https://www.samsung.com/us/computing/memory-storage/memory-cards/pro-plus---reader-microsdxc-256gb-mb-md256kb-am/). The computer a Beelink U59 N5105 with Windows on internal nVME

So the patched code is confirmed to work?
Would be nice with 1-5 more people at least so I know I'm not putting something out there again that isn't working ^^

**Comment by madper** [comment]
I just upgrade the archinstall to `archinstall-2.5.3rc1-1` and the installation finally succeed.

**Comment by Torxed** [comment]
Awesome, I'm merging this patch then and I'll tag and release later today :)
Thank you for testing!

Closing as fixed in #1645

**Comment by millerjs2** [comment]
FYI this issue has not been resolved. Just encountered it today on the latest iso. See attached screenshot and log.

![IMG_1807](https://github.com/archlinux/archinstall/assets/3466374/5bfd9030-d3bb-4676-8d25-0d940adb30cf)
[install.log](https://github.com/archlinux/archinstall/files/11533703/install.log)

**Comment by svartkanin** [comment]
The latest iso doesn't contain the patch yet, you should be able to get it with 
pacman -S archinstall

**Comment by skywa04885** [comment]
Lmfao...... Freaking pulling out the flash-drive made it work after messing around for HOURS! As @RustyRaptor said: Modern problems require modern solutions. LOL

**Comment by luyu-wu** [comment]
![IMG_20230807_170617](https://github.com/archlinux/archinstall/assets/116970666/152c47e8-6d09-4c07-8552-ecc2731411a5)
Strangely still happening to me on the latest ISO and ARCHINSTALL version!
All disks unplugged except for the targeted SATA SSD.

**Comment by dualfade** [comment]
did you upgrade first before running archinstall ? That is what I did and it worked fine after. In mem upgrade in essence. 

------- Original Message -------

**Comment by luyu-wu** [comment]
Yeah, I did, although the August 2023 ISO has the latest version by default. Tried a few times doing things in various chronological orders, all failed!

**Comment by dualfade** [comment]
huh not sure then. Been a few months since I had that issue. Could be something else maybe. Best of luck !!! 
------- Original Message -------

**Comment by alf-lmint** [comment]
> > Guys - if it's of any help to anyone - I just tried the August 2022 ISO, and it worked perfectly.
> > All you have to do is run `pacman-key --init`, `pacman-key --populate archlinux`, and then `archinstall`. I've completed two separate installs using this method today, with no trouble whatsoever. Booting from the ISO directly, or through Ventoy, and even installing to an external USB hard drive - works perfectly. I use the "Wipe all drives" option, take your pick which desktop etc you want - no problem at all.
> > The newer ISO's will work _occasionally_, but I find them very hit and miss. Whatever they did on the August 2022 ISO, they did it right.
> > I hope this might be helpful. Happy to try more testing etc. if that would help.
> 
> I'm using the latest ISO version, with 3 drives on laptops it works smoothly without having to remove any drives

Thanks dayatnhbtc.
Worked beautifully for me, too!

**Comment by breynard0** [comment]
> Here are improved instructions to patch this issue until it's fixed:
> 
>     1. Boot archiso.
> 
>     2. Run `lsblk`:
> 
> 
> ```
> root@archiso ~ # lsblk
> NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
> loop0         7:0    0 705.6M  1 loop /run/archiso/airootfs
> sda           8:0    1  29.9G  0 disk
> └─sda2        8:2    1    15M  0 part
> nvme0n1     259:0    0 476.9G  0 disk
> ├─nvme0n1p1 259:1    0   100M  0 part
> ├─nvme0n1p2 259:2    0   128M  0 part
> ├─nvme0n1p3 259:3    0   475G  0 part
> └─nvme0n1p4 259:4    0   1.7G  0 part
> ```
> 
>     3. Observe the MAJ number of the device that causes archinstall to fail. For me, it was the /dev/sda flash drive which archiso booted off of. I note that /sda has a MAJ value of 8.
> 
>     4. Run this patch command, editing the `-e 8` portion to match the MAJ of the device that's erroring for you.
>        Note: this command recursively edits every instance of lsblk run by archinstall to exclude the specific device.
>        `find /usr/lib/python3.10/site-packages/archinstall/ -type f -exec sed -i "s/lsblk --json/lsblk -a -e 8 --json/g" {} \;`
> 
>     5. Run `archinstall` and install on the desired drive.

This worked for me, thank you.

**Comment by malventano** [comment]
> This worked for me, @tacomilkshake. Thank you.

Was it a recent version ISO you were using? Surely this has been corrected by now... right?

**Comment by breynard0** [comment]
> > This worked for me, @tacomilkshake. Thank you.
> 
> 
> 
> Was it a recent version ISO you were using? Surely this has been corrected by now... right?

@malventano I was using an up-to-date version of the ISO, however I was trying running archinstall from my personal computer, trying to install Arch on a USB stick. Perhaps that messed with things.

**Comment by krisvek** [comment]
> > > This worked for me, @tacomilkshake. Thank you.
> > 
> > 
> > Was it a recent version ISO you were using? Surely this has been corrected by now... right?
> 
> @malventano I was using an up-to-date version of the ISO, however I was trying running archinstall from my personal computer, trying to install Arch on a USB stick. Perhaps that messed with things.

Using the most recent ISO, I just today experienced this same issue installing to a real PC system from USB install media.
The instructions that @tacomilkshake shared a couple of years ago appeared to bypass the problem for me as well.

**Comment by arminask** [comment]
Still not fixed on latest iso.

**Comment by svartkanin** [comment]
Could you share the log so we can debug it better?

**Comment by arminask** [comment]
> Could you share the log so we can debug it better?

Oh sorry, I was in a bit of a hurry so I didn't have time to do that, but I fixed it by ugrading the archinstall package  :)

**Comment by Hugo-Gomez** [comment]
If it helps, running fdisk and deleting all partitions before running `archinstall` again did the trick.
Thanks to the developers for this script, it's a really cool !

**Comment by vagnerlandio** [comment]
> Same here on bare-metal, tried enought times to be sure it doesn't work at all. Tried resetting the keyring as mentioned in #1389:
> 
> ```
> killall gpg-agent
> pacman-key --init
> pacman-key --populate archlinux
> pacman -Syy
> ```
> 
> And... no difference. I hadn't gone trough the manual install for a long time !

Today I have the same problem and this solved my issue, thank you!

**Comment by dualfade** [comment]
Try changing the blackarch-mirrors. I had https://au,mirrors.cicku.me cause this yesterday. Commenting out and swapped to another and the error stopped.

Start with only:
Server = https://ftp.halifax.rwth-aachen.de/blackarch/$repo/os/$arch

And see if the error stops. Until sha1 signing is ultimately resolved there will continue to be errors. Known issue.  You can also re install strap.sh and go back to default settings. 
https://www.blackarch.org/downloads.html#install-repo

Hopefully this helps.

~>D

**Comment by dualfade** [comment]
Apologies. Wrong list --

Sincerely,
