### ISSUE TITLE
"Unable to determine new uuid" error when installing archinstall

### ISSUE THREAD

**Issue by emir4169** [archlinux/archinstall#2305]
im having a "Unable to determine new uuid" error when installing archinstall
[heres the logs](https://0x0.st/HYe5.log)

**Comment by codefiles** [comment]
The device wiping logic and/or udev synchronization could be the cause of the issue. Adding logging for the output of the `mkfs` command may provide additional information.

### Log analysis

I see two runs in the log. On the first run it worked!

```
Formatting filesystem: /usr/bin/mkfs.btrfs -f /dev/nvme0n2p2
partition information found: {'name': 'nvme0n2p2', 'path': '/dev/nvme0n2p2', 'pkname': 'nvme0n2', 'size': '130558 MiB', 'log_sec': 512, 'pttype': 'gpt', 'ptuuid': 'f545e03c-428a-44df-87cc-e8525a70481a', 'rota': False, 'tran': 'nvme', 'partn': 2, 'partuuid': '2f533a5d-d865-4fe3-bcab-b190dcb6cfd4', 'parttype': '0fc63daf-8483-4772-8e79-3d69d8477de4', 'uuid': '0a07e1aa-ea2e-4769-b761-3fe33c6564be', 'fstype': 'btrfs', 'fsver': None, 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
```

Then on the second it did not.

```
Formatting filesystem: /usr/bin/mkfs.btrfs -f /dev/nvme0n2p2
Unable to determine new uuid: /dev/nvme0n2p2
LsblkInfo(name='nvme0n2p2', path=PosixPath('/dev/nvme0n2p2'), pkname='nvme0n2', size=Size(value=136899985408, unit=<Unit.B: 1>, sector_size=SectorSize(value=512, unit=<Unit.B: 1>)), log_sec=512, pttype='gpt', ptuuid='6866456c-50d0-407d-9d9c-1ac8c97f60a2', rota=False, tran='nvme', partn=2, partuuid='082cb0b3-4695-49f6-880b-20c5d6b1e785', parttype='0fc63daf-8483-4772-8e79-3d69d8477de4', uuid=None, fstype=None, fsver=None, fsavail=None, fsuse_percentage=None, type='part', mountpoint=None, mountpoints=[], fsroots=[], children=[])
```

This is the same error seen in the log provided by @LeviSnoot in https://github.com/archlinux/archinstall/issues/2286#issuecomment-1845094905.

```
Formatting filesystem: /usr/bin/mkfs.btrfs -f /dev/nvme1n1p2
Unable to determine new uuid: /dev/nvme1n1p2
LsblkInfo(name='nvme1n1p2', path=PosixPath('/dev/nvme1n1p2'), pkname='nvme1n1', size=Size(value=999666221056, unit=<Unit.B: 1>, sector_size=SectorSize(value=512, unit=<Unit.B: 1>)), log_sec=512, pttype='gpt', ptuuid='480527ce-2a5b-442b-bf40-e8efaf6e17f8', rota=False, tran='nvme', partn=2, partuuid='b9e6eeb3-1fda-4dbd-8024-028323825766', parttype='0fc63daf-8483-4772-8e79-3d69d8477de4', uuid=None, fstype=None, fsver=None, fsavail=None, fsuse_percentage=None, type='part', mountpoint=None, mountpoints=[], fsroots=[], children=[])
```

 It should be noted that the issue title of #2286 states _partition UUID_ while this issue is for _UUID_. A _partition UUID_ [1] is related to partitioning GPT disks specifically and _UUID_ is related to formatting and filesystems [2].

### Device wiping logic

The logic for wiping a device must come from the pyparted example [make_one_primary_partition.py](https://github.com/dcantrell/pyparted/blob/d5870bb7a5d512c17c92a4e4fe7e9a8e7c8c3528/examples/make_one_primary_partition.py).

https://github.com/archlinux/archinstall/blob/f107104103b74ac065a56bd94a0878f0d263e177/archinstall/lib/disk/device_handler.py#L658-L661

https://github.com/archlinux/archinstall/blob/f107104103b74ac065a56bd94a0878f0d263e177/archinstall/lib/disk/device_handler.py#L642-L649

This will not work for Btrfs because the offset of the filesystem signature `0x10040` (or 65600 bytes) is not within the `bytearray(1024)`. The `wipefs` command can be used to observe this. [3]

<details>

<summary>Demonstration</summary>

```
# lsblk name,fstype,uuid /dev/vdb
NAME   FSTYPE UUID
vdb
├─vdb1 vfat   E33B-EDB2
└─vdb2 btrfs  a7051e7b-d853-486b-b7bb-e051a0e07e9d
# wipefs /dev/vdb2
DEVICE OFFSET  TYPE  UUID				  LABEL
vdb2   0x10040 btrfs a7051e7b-d853-486b-b7bb-e051a0e07e9d
# printf "%d\n" 0x10040
65600
# python
Python 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
with open('/dev/vdb2','wb') as p:
	p.write(bytearray(1024))
...
1024
>>>
# lsblk name,fstype,uuid /dev/vdb
NAME   FSTYPE UUID
vdb
├─vdb1 vfat   E33B-EDB2
└─vdb2 btrfs  a7051e7b-d853-486b-b7bb-e051a0e07e9d
# wipefs /dev/vdb2
DEVICE OFFSET  TYPE  UUID				  LABEL
vdb2   0x10040 btrfs a7051e7b-d853-486b-b7bb-e051a0e07e9d
# wipefs -a /dev/vdb2
/dev/vdb2: 8 bytes were erased at offset 0x00010040 (btrfs): 5f 42 48 52 66 53 5f 4d
# lsblk name,fstype,uuid /dev/vdb
NAME   FSTYPE UUID
vdb
├─vdb1 vfat   E33B-EDB2
└─vdb2
# wipefs /dev/vdb2
# exit
```

</details>

Notice in the demonstration that the UUID and offset remained after the write done in python. Following the same steps in the demonstration above but substituting in the EFI system partition (`/dev/vdb1` in the example) will yield different results and the UUID and offset will not show after the write done in python. Why? The furthest out offset for that filesystem signature is `0x1fe` (or 510 bytes) within the range of the `bytearray(1024)`. Test and see! This shows that the code for wiping works when the offset is within the first `1024` bytes but not if it is outside of that range. Any filesystem with an offset outside this range will also have this problem.

A GUID Partition Table has a backup GPT header at the end of the disk that does not get wiped. The offset for the backup GPT header can also be seen in the output of `wipefs`.

To overcome this `wipefs` can be used instead of writing a bytearray.

### Synchronize with udev

The following is from the description of `lsblk(8)`. [4]

> Note that **lsblk** might be executed in time when **udev** does not have all information about recently added or modified devices yet. In this case it is recommended to use **udevadm settle** before **lsblk** to synchronize with udev.

When partitioning and formatting take place during an install there will be at least one recently modified device; `udevadm settle` is not being used as recommended.

### Log format utility output

The output from the `mkfs` utility might be helpful. Notice in the sample output of the `mkfs.btrfs` command below that the UUID is included.

<details>

<summary>Sample command and output</summary>

```
# mkfs.btrfs /dev/vdb2
btrfs-progs v6.6.2
See https://btrfs.readthedocs.io for more information.

Performing full device TRIM /dev/vdb2 (19.50GiB) ...
NOTE: several default settings have changed in version 5.15, please make sure
      this does not affect your deployments:
      - DUP for metadata (-m dup)
      - enabled no-holes (-O no-holes)
      - enabled free-space-tree (-R free-space-tree)

Label:              (null)
UUID:               a7051e7b-d853-486b-b7bb-e051a0e07e9d
Node size:          16384
Sector size:        4096
Filesystem size:    19.50GiB
Block group profiles:
  Data:             single            8.00MiB
  Metadata:         DUP             256.00MiB
  System:           DUP               8.00MiB
SSD detected:       no
Zoned device:       no
Incompat features:  extref, skinny-metadata, no-holes, free-space-tree
Runtime features:   free-space-tree
Checksum:           crc32c
Number of devices:  1
Devices:
   ID        SIZE  PATH     
    1    19.50GiB  /dev/vdb2
```

</details>

What is the output when the error this issue reports is raised? If the output of this command was logged then it could be examined in this case, but it is not.

### References
[1] https://wiki.archlinux.org/title/Persistent_block_device_naming#by-partuuid
[2] https://wiki.archlinux.org/title/Persistent_block_device_naming#by-uuid
[3] https://man.archlinux.org/man/wipefs.8
[4] https://man.archlinux.org/man/lsblk.8#DESCRIPTION

**Comment by codefiles** [comment]
Anyone that can reproduce this error that can try this simple patch?

```patch
diff --git a/archinstall/lib/disk/device_handler.py b/archinstall/lib/disk/device_handler.py
index fcf52013..ade8163b 100644
--- a/archinstall/lib/disk/device_handler.py
+++ b/archinstall/lib/disk/device_handler.py
@@ -316,6 +316,7 @@ class DeviceHandler(object):
                        else:
                                self._perform_formatting(part_mod.safe_fs_type, part_mod.safe_dev_path)

+                       SysCommand('udevadm settle')
                        lsblk_info = self._fetch_part_info(part_mod.safe_dev_path)

                        part_mod.partn = lsblk_info.partn
```

**Comment by uricot** [comment]
Any updates on this? That patch doesn't fix it for me.

**Comment by codefiles** [comment]
I have a few patches I will submit once merge activity for the repo picks back up. Other than that there is no update and if nothing new is posted here then that means nothing has changed.

**Comment by benduckwdesign** [comment]
I just wanted to add that I also encountered this issue and I hope it gets resolved. I tried to work around it by not formatting any btrfs partitions but I encountered a different issue #2317 .

**Comment by codefiles** [comment]
With the logs submitted so far, the UUID is not able to be determined for a partition formatted as Btrfs when a Btrfs file system was previously present at the same device path, which can be seen in the `Disk states before installing` portion of the logs. This appears to support the information I provided regarding the device wiping logic.

It would be helpful if anyone that can reproduce this issue could test the following simple patch.

```patch
diff --git a/archinstall/lib/disk/device_handler.py b/archinstall/lib/disk/device_handler.py
index fcf52013..eb5163b0 100644
--- a/archinstall/lib/disk/device_handler.py
+++ b/archinstall/lib/disk/device_handler.py
@@ -655,10 +655,9 @@ class DeviceHandler(object):
                auto-discovery tools don't recognize anything here.
                """
                info(f'Wiping partitions and metadata: {block_device.device_info.path}')
-               for partition in block_device.partition_infos:
-                       self._wipe(partition.path)
-
-               self._wipe(block_device.device_info.path)
+               paths = [str(part.path) for part in block_device.partition_infos]
+               paths.append(str(block_device.device_info.path))
+               SysCommand(['wipefs', '--all'] + paths)


 device_handler = DeviceHandler()
```

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Is there a way i can use archinstall right now?

**Comment by svartkanin** [comment]
> Is there a way i can use archinstall right now? 

You can try the patch from @codefiles https://github.com/archlinux/archinstall/issues/2305#issuecomment-1874724212

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I don't know how I can apply the patch to the archinstall script

**Comment by codefiles** [comment]
> I don't know how I can apply the patch to the archinstall script

The easiest way to test the logic of the patch would be to run a <code>wipefs -a <i>device</i></code> command before the `archinstall` command, where <i>device</i> is the device from the error message. In #2322 your error message was `Unable to determine new uuid: /dev/nvme0n1p2` so try `wipefs -a /dev/nvme0n1p2`. That should be sufficient to test what the patch does with the least amount of trouble, please report back.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I don't think it worked as I understood you you said running wipefs -a /dev... should have the same affect as your fix but it didn't work for me 
https://0x0.st/H60v.log

**Comment by codefiles** [comment]
It looks like you understood just fine. This is from the log under the `Disk states before installing` portion of the first run.

```
            {
                ...
                "fstype": "vfat",
                ...
                "partuuid": "42ab6fc9-2917-4840-83b7-54437ef72b80",
                "path": "/dev/nvme0n1p1",
                ...
                "uuid": "C49A-C194"
            },
            {
                ...
                "fstype": null,
                ...
                "partuuid": "93b2c2c3-e841-4aab-a9e4-11a3dd535b59",
                "path": "/dev/nvme0n1p2",
                ...
                size": "1024 MiB",
                ...
                "uuid": null
            },
            {
                ...
                "fstype": "btrfs",
                ...
                "partuuid": "8222a227-f888-429f-943f-2beefb6ee1e4",
                "path": "/dev/nvme0n1p3",
                ...
                "size": "1906104 MiB",
                ...
                "uuid": "f7802a0f-a52c-4e6f-ac3e-0b2c15ac432e"
            }
```

The `fstype` of `/dev/nvme01p2` is null and so is the `uuid`, that shows that you did the `wipefs` command correctly.

Could you also try `wipefs -a /dev/nvme0n1*` before the `archinstall` command?

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Still doesn't seem to work
https://0x0.st/H6GW.log

**Comment by codefiles** [comment]
Could you run `lsblk -n -o uuid /dev/nvme0n1p2` after that combination? Do you get any output?

**Comment by Schweeeeeeeeeeeeeeee** [comment]
![PXL_20240106_163342284](https://github.com/archlinux/archinstall/assets/88291316/bcf66471-4343-4526-ae07-2f24b9b866ac)

**Comment by codefiles** [comment]
Could you run the `lsblk` command right after getting the error message?

**Comment by Schweeeeeeeeeeeeeeee** [comment]
![PXL_20240106_164010214](https://github.com/archlinux/archinstall/assets/88291316/a06c0e81-2239-4ce0-a41e-04441c325d2b)

**Comment by codefiles** [comment]
Now do precisely this:

```
wipefs -a /dev/nvme0n1p2
mkfs.btrfs /dev/nvme0n1p2
lsblk -n -o uuid /dev/nvme0n1p2
```

**Comment by Schweeeeeeeeeeeeeeee** [comment]
![Uploading PXL_20240106_164429679.jpg…]()

**Comment by Schweeeeeeeeeeeeeeee** [comment]
![PXL_20240106_164429679](https://github.com/archlinux/archinstall/assets/88291316/ad22a996-fdca-47f1-9e29-574bec291764)

**Comment by codefiles** [comment]
Thank you so much @Schweeeeeeeeeeeeeeee! You have verified that #2211 is correct for this issue. We can see you clearly can trigger the error but when the commands above are supplied there is no problem with getting the uuid.

This leads me back to https://github.com/archlinux/archinstall/issues/2305#issuecomment-1859350259. To many apply the patch from that comment, on the live ISO manually edit the file `/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py` and add `SysCommand('udevadm settle')` on the line above line number 319 which is `lsblk_info = self._fetch_part_info(part_mod.safe_dev_path)`, use the same indentation as this line. Then save the file and run `wipefs -a nvme0n1*` followed by `archinstall`.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Yeah I just installed archinstall on another distro and added the line there and got the same error

**Comment by codefiles** [comment]
If you repeat https://github.com/archlinux/archinstall/issues/2305#issuecomment-1879750945 but use the force option to format Btrfs like `mkfs.btrfs -f /dev/nvme0n1p2` is the uuid available in the output of the `lsblk` command?

I am going to review the code that handles this part a little closer.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Did this on my old drive running arch
![image](https://github.com/archlinux/archinstall/assets/88291316/c04ddd51-526d-4873-a882-b941e1f9e303)

**Comment by codefiles** [comment]
Sorry we did not arrive at a fix just yet but we did acquire new information.

- Wiping the device with `wipefs` does not appear to make a difference
- After the error the uuid is confirmed to not be available after a time delay so a `udevadm settle` would not make a difference
- A uuid is available for Btrfs after a manual format with the same hardware that triggers the error
- The force option for `mkfs.btrfs` does not matter

I think if I can get a few fixes merged for some of the issues I have notices like #2294 then this might get solved by the logic clean up in those fixes.

**Comment by codefiles** [comment]
Looks like this happens when the file system is Btrfs both with and without subvolumes. Does this also happen when the file system is ext4?

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Seems like it works with ext4

**Comment by Schweeeeeeeeeeeeeeee** [comment]
I just tried to install arch with ext4 with the config i actually want and im not sure but i think it failed again in the same way
![image](https://github.com/archlinux/archinstall/assets/88291316/e7d64c87-0c49-4859-bfe9-89f196cc7c38)
I clearly selected exFAT, but can't find it in the log I find btrfs even though I didn't select it (I just hit ctrl f i can't actually analyze it)

**Comment by codefiles** [comment]
This is not the same error, it is unrelated.

```
archinstall.lib.exceptions.SysCallError: ['/usr/bin/umount', '-R', '/mnt/archinstall'] exited with abnormal exit code [32]: umount: /mnt/archinstall: target is busy.
```

You could try `umount -l -R /mnt/archinstall` before installing or it may require a reboot.

**Comment by Dlinuigh** [comment]
Just mkfs.different fs from before device name to get the partition a new uuid.
This work for me.
But I want to report a problem: after choose unified kernel and grub cause booting stop at loading initial ramdisk

**Comment by Dlinuigh** [comment]
> Just mkfs.different fs from before device name to get the partition a new uuid. This work for me. But I want to report a problem: after choose unified kernel and grub cause booting stop at loading initial ramdisk

oops, not working with this method.
before mkfs the log is 0x0.st/HIHE.log
after mkfs the log is 0x0.st/HIHU.log

**Comment by Dlinuigh** [comment]
not working anymore. What leads this problem should really annoy both users and developers.

**Comment by Dlinuigh** [comment]
Emmm, I overcome this problem by doing this:
```
use fdisk change the partition
# use ioctl() to reread the partition, besides above obviously not a command.
partprobe
# this command is a method to call ioctl()
```

**Comment by phush0** [comment]
Yesterday I had success with install after several retries with same config. Today I can not do it again even after 10 tries

**Comment by elppans** [comment]
Unable to determine new UUID: /dev/sda2

https://0x0.st/HUvz.log

**Comment by vncsna** [comment]
I just had the same problem, as the [logs](https://0x0.st/H0DX.log) show. Then tried this unrelated fix [here](https://github.com/archlinux/archinstall/issues/2286), and the installation progressed

**Comment by elppans** [comment]
I did some tests, this time I didn't generate logs because they are the same
But due to the tests, I came to the conclusion that you have to adapt the archinstall script to Python 3.11.6, as the tests had the following:

1 - ISO 2024.01.01, archinstall 2.7.1-1, python 3.11.6 (Failure)
![ISO 2024.01.01, archinstall 2.7.1-1, python 3.11.6](https://i.imgur.com/ykpYM8f.png)

2 - ISO 2023.11.01, archinstall 2.6.3, python 3.11.5 (Success)
![ISO 2023.11.01, archinstall 2.6.3, python 3.11.5](https://i.imgur.com/jfIYFTw.png)

3 - ISO 2023.11.01, archinstall 2.7.1-1, python 3.11.5 (Success)
![ISO 2023.11.01, archinstall 2.7.1-1, python 3.11.5, install packages](https://i.imgur.com/Ln0JVGx.png)
![ISO 2023.11.01, archinstall 2.7.1-1, python 3.11.5, Result](https://i.imgur.com/uLjdXmo.png)

**Comment by Dlinuigh** [comment]
quiet a log job

> > Just mkfs.different fs from before device name to get the partition a new uuid. This work for me. But I want to report a problem: after choose unified kernel and grub cause booting stop at loading initial ramdisk
> 
> I have confirmed unified kernel false and grub will not cause the problem described above.

my bad, I just mean on my laptop, unified kernel true and use grub as bootloader will cause another problem, this won't solve any existed problem but produce a new one.

**Comment by ioannedelea** [comment]
I see that the arch team already put btrfs-progs in Core-Testing repo. Thank you to @codefiles for his thoroughness and support in this thread. Also, much love to the btrfs-progs devs for moving so fast with the fix.

**Comment by Schweeeeeeeeeeeeeeee** [comment]
😞🔫 I got it by luck thought it was fixed reinstalled arch for something else same bug. https://0x0.st/HDbB.log

**Comment by ioannedelea** [comment]
@codefiles I can confirm that the fix you suggested in the pull request #2354 works very well. I manually edited the device_handler.py with your code and it ran just fine.

**Comment by elppans** [comment]
Today I downloaded the new version of the ISO, **archlinux-2024.02.01-x86_64** and did a test installation.  

This time I did absolutely nothing, just ran the archinstall command.  
With this version everything went well, the first time, **without any errors**.

**Comment by youngwillyum** [comment]
> Emmm, I overcome this problem by doing this:
> 
> ```
> use fdisk change the partition
> # use ioctl() to reread the partition, besides above obviously not a command.
> partprobe
> # this command is a method to call ioctl()
> ```

This fixed for me as-well, installing on surface laptop 4. 

As for my  desktop with nvme / btrfs, i just had to zap the disk and it installed just fine.


Thank you sir.

**Comment by kstr0git** [comment]
> Today I downloaded the new version of the ISO, **archlinux-2024.02.01-x86_64** and did a test installation.
> 
> This time I did absolutely nothing, just ran the archinstall command. With this version everything went well, the first time, **without any errors**.

Did you use btrfs file system when formatting your drive? I still encountered this issue. Fortunately it does look like pull request #2354 seems to be the solve for this. I was able to manually patch device_handler.py and then archinstall ran fine.

**Comment by Peekabooxi** [comment]
Tried today with newest iso. Got #2305. tried multiple times with different settings. Works with ext4 though

**Comment by codefiles** [comment]
The v6.7.1 release of btrfs-progs contains a fix (https://github.com/kdave/btrfs-progs/commit/e54514aaeab6be64679787e78679e8eb700740f6) that should resolve this issue. This is the version that is now available in the Arch Linux repos.

Run the following commands before running archinstall from the latest ISO.

```
ln -sf /dev/null /usr/share/libalpm/hooks/90-mkinitcpio-install.hook
pacman -Sy btrfs-progs
```

This will update btrfs-progs and the symlink will prevent the ISO initrd from being rebuilt following the update by [disabling the hook](https://man.archlinux.org/man/alpm-hooks.5#OVERRIDING_HOOKS).

**Comment by moritz-t-w** [comment]
@codefiles answer fixed it for me.

**Comment by Peekabooxi** [comment]
Just fresh installed and can confirm the fix works.

**Comment by VhMuzini** [comment]
> The v6.7.1 release of btrfs-progs contains a fix ([kdave/btrfs-progs@e54514a](https://github.com/kdave/btrfs-progs/commit/e54514aaeab6be64679787e78679e8eb700740f6)) that should resolve this issue. This is the version that is now available in the Arch Linux repos.
> 
> To try this fix with the latest ISO run the following commands before running archinstall.
> 
> ```
> ln -sf /dev/null /usr/share/libalpm/hooks/90-mkinitcpio-install.hook
> pacman -Sy btrfs-progs
> ```
> 
> This will update btrfs-progs and create a symlink that will prevent the ISO initramfs from being rebuilt (since that may cause an error and the ISO is non-persistent anyway) following this update by [disabling the relevant hook](https://man.archlinux.org/man/alpm-hooks.5#OVERRIDING_HOOKS).
> 
> If this takes care of the issue then it will resolve itself in the next ISO release.

This fix worked for me.

**Comment by Hanqnero** [comment]
> > The v6.7.1 release of btrfs-progs contains a fix ([kdave/btrfs-progs@e54514a](https://github.com/kdave/btrfs-progs/commit/e54514aaeab6be64679787e78679e8eb700740f6)) that should resolve this issue. This is the version that is now available in the Arch Linux repos.
> > To try this fix with the latest ISO run the following commands before running archinstall.
> > ```
> > ln -sf /dev/null /usr/share/libalpm/hooks/90-mkinitcpio-install.hook
> > pacman -Sy btrfs-progs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will update btrfs-progs and create a symlink that will prevent the ISO initramfs from being rebuilt (since that may cause an error and the ISO is non-persistent anyway) following this update by [disabling the relevant hook](https://man.archlinux.org/man/alpm-hooks.5#OVERRIDING_HOOKS).
> > If this takes care of the issue then it will resolve itself in the next ISO release.
> 
> This fix worked for me.

After getting same issue I ran `pacman -Syy btrfs-progs` and did not encounter the issue with same disk configuration

**Comment by elppans** [comment]
> > Today I downloaded the new version of the ISO, **archlinux-2024.02.01-x86_64** and did a test installation.
> > This time I did absolutely nothing, just ran the archinstall command. With this version everything went well, the first time, **without any errors**.
> 
> @elppans Você usou o sistema de arquivos btrfs ao formatar sua unidade? Ainda encontrei esse problema. Felizmente parece que o pull request #2354 parece ser a solução para isso. Eu era capaz de corrigir manualmente device_handler.py e, em seguida, archinstall funcionou bem seguindo as sugestões do .

Yes, I used BTRFS file system and everything went fine. I even posted the [Screenshot images on my github](https://elppans.github.io/doc-linux/archinstall_img_archlinux-2024.02.01-x86_64) to show how I installed it.
As I am Brazilian, the page is in Portuguese, but what matters are the images.
The tenth image shows the configuration of the partitions.
