### ISSUE TITLE
Problem at master with translations

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#963]
Trying to start an installation script in master I get
```
[werner@xerneas archinstall]$ sudo python -m archinstall --script only_hd --dry_run
Testing connectivity to the Arch Linux mirrors ...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/werner/projects/archinstall/archinstall/__main__.py", line 15, in <module>
    archinstall.run_as_a_module()
  File "/home/werner/projects/archinstall/./archinstall/__init__.py", line 267, in run_as_a_module
    script.execute()
  File "/home/werner/projects/archinstall/archinstall/lib/profiles.py", line 194, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/werner/projects/archinstall/archinstall/examples/only_hd.py", line 123, in <module>
    ask_user_questions()
  File "/home/werner/projects/archinstall/archinstall/examples/only_hd.py", line 44, in ask_user_questions
    with OnlyHDMenu(data_store=archinstall.arguments) as menu:
  File "/home/werner/projects/archinstall/archinstall/lib/menu/selection_menu.py", line 402, in __init__
    super().__init__(data_store=data_store)
  File "/home/werner/projects/archinstall/archinstall/lib/menu/selection_menu.py", line 178, in __init__
    self._translation = Translation.load_nationalization()
  File "/home/werner/projects/archinstall/archinstall/lib/translation.py", line 74, in load_nationalization
    return Translation(locales_dir)
  File "/home/werner/projects/archinstall/archinstall/lib/translation.py", line 63, in __init__
    self._languages[name] = gettext.translation('base', localedir=locales_dir, languages=[name])
  File "/usr/lib/python3.10/gettext.py", line 592, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'base'
```
I've tried reverting the dutch (this seems to lack a .mo file)  and french translation commits and my own commit. The error keeps happening. I have no clue

**Comment by Torxed** [comment]
It seams that the file names was incorrectly named. https://github.com/archlinux/archinstall/blob/master/archinstall/locales/nl/LC_MESSAGES/nl.po for instance should be `base.po` and not `nl.po`.

**Comment by Torxed** [comment]
I pushed some code to `master` that should at least make it easier to distinguish which file it's missing. Hopefully it will tell us which language is causing the issue :)

**Comment by wllacer** [comment]
The error happens when processing the dutch translation (according to my traces). Unlike the other directories, it misses an .mo file.
To add problems the revert didn't "delete" the directory, that's what it is still happening to me.
After a manual intervention I can confirm, it is the dutch translation which fails

**Comment by Torxed** [comment]
> The error happens when processing the dutch translation (according to my traces). Unlike the other directories, it misses an .mo file. To add problems the revert didn't "delete" the directory, that's what it is still happening to me. After a manual intervention I can confirm, it is the dutch translation which fails

I'll see if I can fix it tonight. Just need to open the editor program thingie that @svartkanin recommended.

**Comment by svartkanin** [comment]
Wow I'm extremely surprised how many translation contributions this has received in this short timeframe. I was honestly sceptical about if anyone would bother choosing anything but English but this is incredible!

**Comment by dylanmtaylor** [comment]
> Took me by surprise as well hehe. I’m on my way to submit one more translation ^^

I'm going to give it a while to guess and say swedish?

**Comment by Torxed** [comment]
> > Took me by surprise as well hehe. I’m on my way to submit one more translation ^^
> 
> I'm going to give it a wild guess and say swedish?

Haha, 10/10 guess xD
